version: '3.8'
# Don`t touch unless u know what u are doing!
services:
  bank-db:
    image: postgres
    container_name: bank-db
    environment:
      POSTGRES_DB: BankServiceDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"

  iam-db:
    image: postgres
    container_name: iam-db
    environment:
      POSTGRES_DB: IamServiceDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      POSTGRES_DB: NotificationServiceDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"

  stock-db:
    image: postgres
    container_name: stock-db
    environment:
      POSTGRES_DB: StockServiceDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5436:5432"

  stock-redis:
    image: redis
    expose:
      - "6379"
    container_name: stock-redis
    environment:
      REDIS_HOST_AUTH_METHOD: trust
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: my-rabbit-host
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitdata:/var/lib/rabbitmq"

#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASSWORD: guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5

  bank-service:
    build: ./BankService
    container_name: bank-service
    ports:
      - "8003:8003"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bank-db:5432/BankServiceDB
    depends_on:
      - bank-db
      - rabbitmq

  iam-service:
    build: ./IAMService
    container_name: iam-service
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iam-db:5432/IamServiceDB
    depends_on:
      - iam-db
      - rabbitmq

  notification-service:
    build: ./NotificationService
    container_name: notification-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-db:5432/NotificationServiceDB
    depends_on: #conditions for service to start, its a black magic dont touch unless u know what u are doing!
      notification-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  
  stock-service:
    build: ./StockService
    container_name: stock-service
    ports:
      - "8001:8001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stock-db:5432/StockServiceDB
      - SPRING_REDIS_HOST=stock-redis
    depends_on:
      - stock-db
      - rabbitmq
      - stock-redis